DELIMITER //

CREATE TRIGGER GenerateCouponCode BEFORE INSERT ON Promotions
FOR EACH ROW
BEGIN
    SET NEW.CouponCode = CONCAT('PROMO', LPAD(FLOOR(1000 + RAND() * 9000), 4, '0'));
END //

DELIMITER ;
